import type { Category, Service, Testimonial } from "./types";

/**
 * The storefront catalog.
 *
 * This is the single source of truth used to seed Supabase (see
 * `supabase/seed.sql`) and the fallback the site renders from when Supabase
 * credentials are not configured, so the store is never empty.
 */

export const categories: Category[] = [
  {
    id: "cat-social",
    slug: "social",
    name: "خدمات السوشيال ميديا",
    tagline: "متابعين • لايكات • مشاهدات",
    description:
      "رفع حسابك على كل المنصات بمتابعين ولايكات ومشاهدات حقيقية التفاعل، مع بدء سريع وضمان تعويض النقص.",
    icon: "TrendingUp",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "cat-usernames",
    slug: "usernames",
    name: "اليوزرات المميزة",
    tagline: "أسماء نادرة بأحرف وأرقام قليلة",
    description:
      "يوزرات إنستقرام وسناب شات وتيك توك وتليجرام مميزة — ٣ و٤ حروف، أسماء نادرة، نقل ملكية آمن وموثّق.",
    icon: "AtSign",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "cat-subscriptions",
    slug: "subscriptions",
    name: "الاشتراكات الرقمية",
    tagline: "ترفيه • إبداع • ذكاء اصطناعي",
    description:
      "اشتراكات أصلية بأسعار منافسة: منصات الأفلام والموسيقى، أدوات التصميم، وأقوى أدوات الذكاء الاصطناعي.",
    icon: "Sparkles",
    sort_order: 3,
    is_active: true,
  },
  {
    id: "cat-gaming",
    slug: "gaming",
    name: "بطاقات الشحن والألعاب",
    tagline: "شحن فوري لكل الألعاب",
    description:
      "شحن شدات ببجي، جواهر فري فاير، بطاقات جوجل بلاي وآيتونز وستيم وبلايستيشن — تسليم خلال دقائق.",
    icon: "Gamepad2",
    sort_order: 4,
    is_active: true,
  },
  {
    id: "cat-telecom",
    slug: "telecom",
    name: "باقات الاتصالات",
    tagline: "إنترنت • مكالمات • تعبئة رصيد",
    description:
      "باقات جوال وأوريدو، تعبئة رصيد فورية، وباقات الإنترنت الشهرية بأفضل سعر وتفعيل مباشر.",
    icon: "Signal",
    sort_order: 5,
    is_active: true,
  },
  {
    id: "cat-digital",
    slug: "digital",
    name: "الخدمات الرقمية والتصميم",
    tagline: "هوية • تسويق • محتوى",
    description:
      "نصنع حضورك الرقمي من الصفر: هوية بصرية، تصميم مواقع، إدارة إعلانات وحسابات، ومحتوى يبيع.",
    icon: "Palette",
    sort_order: 6,
    is_active: true,
  },
  {
    id: "cat-other",
    slug: "other",
    name: "خدمات أخرى",
    tagline: "توثيق • استرجاع • حماية",
    description:
      "توثيق الحسابات بالعلامة الزرقاء، استرجاع الحسابات المسروقة أو المغلقة، حماية، دومينات واستضافة.",
    icon: "ShieldCheck",
    sort_order: 7,
    is_active: true,
  },
];

export const services: Service[] = [
  // ── خدمات السوشيال ميديا ────────────────────────────────────────────────
  {
    id: "svc-ig-followers",
    category_slug: "social",
    slug: "instagram-followers",
    title: "متابعين إنستقرام",
    summary: "متابعين عرب بجودة عالية وتفاعل حقيقي مع ضمان تعويض النقص ٣٠ يوم.",
    description:
      "زيادة متابعين إنستقرام بحسابات نشطة وصور شخصية ومنشورات، بسرعة إضافة طبيعية تحمي حسابك من أي إنذار. تختار العدد ونحن نبدأ خلال دقائق من تأكيد الطلب.",
    price: 15,
    old_price: 22,
    currency: "₪",
    unit: "لكل 1000",
    delivery_time: "يبدأ خلال 5 دقائق",
    features: [
      "حسابات عربية بمظهر حقيقي",
      "ضمان تعويض النقص لمدة 30 يوم",
      "لا يحتاج كلمة المرور — اليوزر فقط",
      "سرعة إضافة آمنة ومتدرجة",
    ],
    badge: "الأكثر طلباً",
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "svc-ig-likes",
    category_slug: "social",
    slug: "instagram-likes",
    title: "لايكات إنستقرام",
    summary: "لايكات فورية على أي منشور أو ريلز لرفع الوصول والاكسبلور.",
    description:
      "لايكات تصل خلال دقائق على المنشور أو الريلز الذي تختاره، تساعد على دفع المحتوى للاكسبلور وزيادة الوصول الطبيعي.",
    price: 6,
    old_price: 10,
    currency: "₪",
    unit: "لكل 1000",
    delivery_time: "فوري — خلال دقائق",
    features: [
      "بدء فوري بعد الطلب",
      "توزيع طبيعي غير مفاجئ",
      "يعمل على البوستات والريلز",
      "بدون كلمة مرور",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 2,
  },
  {
    id: "svc-tiktok-followers",
    category_slug: "social",
    slug: "tiktok-followers",
    title: "متابعين تيك توك",
    summary: "بناء جمهور تيك توك بسرعة آمنة تدعم ظهورك في الـ For You.",
    description:
      "متابعين تيك توك بجودة ممتازة وسرعة إضافة مدروسة، مثالية للحسابات الجديدة التي تريد الوصول لشروط البث المباشر والتحقيق.",
    price: 18,
    old_price: 26,
    currency: "₪",
    unit: "لكل 1000",
    delivery_time: "يبدأ خلال 10 دقائق",
    features: [
      "يساعد على الوصول لشرط البث المباشر",
      "ضمان تعويض 30 يوم",
      "إضافة تدريجية آمنة",
      "دعم لكل الدول",
    ],
    badge: "الأسرع نمواً",
    is_featured: true,
    is_active: true,
    sort_order: 3,
  },
  {
    id: "svc-tiktok-views",
    category_slug: "social",
    slug: "tiktok-views",
    title: "مشاهدات تيك توك",
    summary: "دفعة مشاهدات قوية لأي فيديو لزيادة فرص الانتشار.",
    description:
      "مشاهدات حقيقية المصدر تُضاف على الفيديو المحدد، تُستخدم لإعطاء الفيديو دفعة أولى تساعد الخوارزمية على توزيعه.",
    price: 4,
    old_price: null,
    currency: "₪",
    unit: "لكل 10,000",
    delivery_time: "فوري — خلال دقائق",
    features: [
      "أرخص سعر في السوق",
      "بدء فوري",
      "لا يؤثر على الحساب",
      "متاح لأي عدد",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: "svc-snap-followers",
    category_slug: "social",
    slug: "snapchat-followers",
    title: "متابعين سناب شات",
    summary: "زيادة متابعي سناب شات ورفع نسبة مشاهدات الستوري.",
    description:
      "متابعين سناب شات مع تحسين ملحوظ في عدد مشاهدات الستوري اليومية، مناسب للمتاجر والمشاهير الجدد.",
    price: 28,
    old_price: 40,
    currency: "₪",
    unit: "لكل 1000",
    delivery_time: "يبدأ خلال 30 دقيقة",
    features: [
      "رفع مشاهدات الستوري",
      "مناسب للمتاجر الإلكترونية",
      "إضافة آمنة ومتدرجة",
      "دعم فني طوال فترة التنفيذ",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 5,
  },
  {
    id: "svc-youtube-subs",
    category_slug: "social",
    slug: "youtube-subscribers",
    title: "مشتركين يوتيوب",
    summary: "مشتركين لقناتك للوصول لشروط تحقيق الدخل.",
    description:
      "مشتركين يوتيوب بجودة عالية مع ثبات ممتاز، إضافة تدريجية على مدار أيام لضمان أمان القناة والوصول لشروط الشراكة.",
    price: 45,
    old_price: 60,
    currency: "₪",
    unit: "لكل 1000",
    delivery_time: "يبدأ خلال ساعة",
    features: [
      "يساعد على شروط تحقيق الدخل",
      "ثبات عالي جداً",
      "إضافة تدريجية على أيام",
      "ضمان تعويض 60 يوم",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 6,
  },
  {
    id: "svc-telegram-members",
    category_slug: "social",
    slug: "telegram-members",
    title: "أعضاء قنوات تليجرام",
    summary: "أعضاء حقيقيين لقناتك أو جروبك مع نسبة مشاهدة عالية.",
    description:
      "إضافة أعضاء لقناة أو مجموعة تليجرام مع نسبة مشاهدة جيدة للمنشورات، مثالي لقنوات البيع والإعلانات.",
    price: 20,
    old_price: null,
    currency: "₪",
    unit: "لكل 1000",
    delivery_time: "يبدأ خلال 20 دقيقة",
    features: [
      "يعمل للقنوات والمجموعات",
      "نسبة مشاهدة عالية",
      "بدون صلاحية إدارة",
      "تعويض النقص متاح",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 7,
  },
  {
    id: "svc-live-views",
    category_slug: "social",
    slug: "live-stream-views",
    title: "مشاهدات بث مباشر",
    summary: "مشاهدين للبث المباشر على إنستقرام أو تيك توك أو يوتيوب.",
    description:
      "مشاهدين يدخلون بثك المباشر ويبقون طوال المدة المحجوزة، مما يرفع ترتيب البث ويجذب جمهوراً حقيقياً.",
    price: 35,
    old_price: null,
    currency: "₪",
    unit: "لكل 500 / ساعة",
    delivery_time: "يُحجز قبل البث بـ 15 دقيقة",
    features: [
      "يبقى المشاهدون طوال البث",
      "يرفع ترتيب البث في المنصة",
      "متاح لكل المنصات",
      "حجز مسبق بموعد محدد",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 8,
  },

  // ── اليوزرات المميزة ────────────────────────────────────────────────────
  {
    id: "svc-user-ig-4",
    category_slug: "usernames",
    slug: "instagram-username-4",
    title: "يوزر إنستقرام رباعي",
    summary: "يوزر من 4 حروف/أرقام — نادر ويرفع قيمة حسابك فوراً.",
    description:
      "يوزرات إنستقرام رباعية متاحة للبيع مع نقل ملكية آمن وشرح كامل للخطوات. تصفح المتاح حالياً وتواصل معنا لحجز اليوزر الذي يعجبك.",
    price: 180,
    old_price: 250,
    currency: "₪",
    unit: null,
    delivery_time: "تسليم خلال 1-3 ساعات",
    features: [
      "نقل ملكية آمن بالكامل",
      "ضمان عدم الاسترجاع",
      "شرح مباشر لكل خطوة",
      "قائمة يوزرات متجددة يومياً",
    ],
    badge: "نادر",
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "svc-user-ig-3",
    category_slug: "usernames",
    slug: "instagram-username-3",
    title: "يوزر إنستقرام ثلاثي",
    summary: "أندر فئة يوزرات — 3 حروف فقط، كمية محدودة جداً.",
    description:
      "يوزرات إنستقرام ثلاثية، الفئة الأندر على الإطلاق. الكمية محدودة والأسعار تختلف حسب جمالية الحرف والطلب عليه.",
    price: 950,
    old_price: null,
    currency: "₪",
    unit: "يبدأ من",
    delivery_time: "تسليم خلال 3-6 ساعات",
    features: [
      "أندر فئة على الإطلاق",
      "توثيق كامل لعملية النقل",
      "وسيط ضمان عند الطلب",
      "استشارة مجانية قبل الشراء",
    ],
    badge: "حصري",
    is_featured: true,
    is_active: true,
    sort_order: 2,
  },
  {
    id: "svc-user-snap",
    category_slug: "usernames",
    slug: "snapchat-username",
    title: "يوزر سناب شات مميز",
    summary: "يوزرات سناب قصيرة ومميزة بأسعار تنافسية.",
    description:
      "يوزرات سناب شات مميزة من 4 و5 حروف، مع نقل ملكية مباشر وضمان كامل بعد التسليم.",
    price: 120,
    old_price: 170,
    currency: "₪",
    unit: null,
    delivery_time: "تسليم خلال 1-3 ساعات",
    features: [
      "يوزرات 4 و5 حروف",
      "نقل ملكية مباشر",
      "ضمان بعد التسليم",
      "أسعار تنافسية",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: "svc-user-tiktok",
    category_slug: "usernames",
    slug: "tiktok-username",
    title: "يوزر تيك توك مميز",
    summary: "احجز اسم علامتك التجارية على تيك توك قبل غيرك.",
    description:
      "يوزرات تيك توك قصيرة وأسماء علامات تجارية محجوزة، مثالية لمن يريد اسماً موحداً على كل المنصات.",
    price: 140,
    old_price: null,
    currency: "₪",
    unit: null,
    delivery_time: "تسليم خلال 2-5 ساعات",
    features: [
      "أسماء علامات تجارية متاحة",
      "توحيد اسمك على كل المنصات",
      "نقل آمن وموثّق",
      "خدمة البحث عن يوزر محدد",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: "svc-user-telegram",
    category_slug: "usernames",
    slug: "telegram-username",
    title: "يوزر تليجرام مميز",
    summary: "يوزرات تليجرام قصيرة لقناتك أو حسابك الشخصي.",
    description:
      "يوزرات تليجرام مميزة وقصيرة، تُنقل مباشرة إلى حسابك أو قناتك خلال دقائق من تأكيد الطلب.",
    price: 95,
    old_price: null,
    currency: "₪",
    unit: null,
    delivery_time: "تسليم خلال ساعة",
    features: [
      "نقل خلال دقائق",
      "يعمل للحسابات والقنوات",
      "أسعار تبدأ من 95₪",
      "قائمة متجددة",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 5,
  },
  {
    id: "svc-user-request",
    category_slug: "usernames",
    slug: "username-hunt",
    title: "خدمة البحث عن يوزر محدد",
    summary: "اطلب اليوزر الذي تريده ونحن نبحث عنه ونتفاوض نيابة عنك.",
    description:
      "أرسل لنا اليوزر الذي تحلم به وسنبحث عن مالكه ونتفاوض على شرائه نيابة عنك، مع إدارة كاملة لعملية النقل والضمان.",
    price: 60,
    old_price: null,
    currency: "₪",
    unit: "رسوم بحث",
    delivery_time: "نتيجة خلال 24-72 ساعة",
    features: [
      "تفاوض احترافي نيابة عنك",
      "رسوم البحث تُخصم من سعر اليوزر",
      "إدارة كاملة لعملية النقل",
      "تقرير بالنتيجة مهما كانت",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 6,
  },

  // ── الاشتراكات الرقمية ──────────────────────────────────────────────────
  {
    id: "svc-sub-chatgpt",
    category_slug: "subscriptions",
    slug: "chatgpt-plus",
    title: "اشتراك ChatGPT Plus",
    summary: "الوصول الكامل لأحدث النماذج بأسرع استجابة وبدون ازدحام.",
    description:
      "اشتراك شهري أصلي يفتح لك أحدث النماذج وأدوات التحليل ورفع الملفات وتوليد الصور، مع أولوية في أوقات الضغط.",
    price: 75,
    old_price: 95,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "تفعيل خلال 15 دقيقة",
    features: [
      "اشتراك أصلي 100%",
      "أحدث النماذج المتاحة",
      "يعمل على حسابك الشخصي",
      "دعم متابعة طوال الشهر",
    ],
    badge: "الأكثر مبيعاً",
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "svc-sub-canva",
    category_slug: "subscriptions",
    slug: "canva-pro",
    title: "اشتراك Canva Pro",
    summary: "كل قوالب وأدوات كانفا الاحترافية لمدة سنة كاملة.",
    description:
      "اشتراك كانفا برو سنوي على إيميلك الشخصي، يفتح ملايين القوالب والصور والخطوط وأدوات إزالة الخلفية والتصدير بجودة عالية.",
    price: 45,
    old_price: 80,
    currency: "₪",
    unit: "سنوياً",
    delivery_time: "تفعيل خلال 10 دقائق",
    features: [
      "سنة كاملة بسعر شهر",
      "على إيميلك الشخصي",
      "كل القوالب والخطوط مفتوحة",
      "إزالة خلفية بنقرة",
    ],
    badge: "أفضل قيمة",
    is_featured: true,
    is_active: true,
    sort_order: 2,
  },
  {
    id: "svc-sub-netflix",
    category_slug: "subscriptions",
    slug: "netflix",
    title: "اشتراك نتفلكس",
    summary: "بروفايل خاص بجودة 4K وثبات مضمون طوال المدة.",
    description:
      "اشتراك نتفلكس ببروفايل مستقل خاص بك بجودة عالية، مع استبدال فوري في حال حصول أي خلل خلال فترة الاشتراك.",
    price: 30,
    old_price: 45,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "تفعيل خلال 15 دقيقة",
    features: [
      "بروفايل خاص لا يشاركك فيه أحد",
      "جودة 4K على الأجهزة الداعمة",
      "استبدال فوري عند أي مشكلة",
      "خصم على الاشتراك الطويل",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: "svc-sub-shahid",
    category_slug: "subscriptions",
    slug: "shahid-vip",
    title: "اشتراك شاهد VIP",
    summary: "كل المسلسلات العربية والحصريات بدون إعلانات.",
    description:
      "اشتراك شاهد VIP يفتح لك المكتبة العربية الكاملة والحصريات والبث المباشر للقنوات بدون أي إعلانات.",
    price: 25,
    old_price: 38,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "تفعيل خلال 15 دقيقة",
    features: [
      "بدون إعلانات",
      "قنوات MBC مباشرة",
      "تحميل للمشاهدة بدون إنترنت",
      "ضمان طوال المدة",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: "svc-sub-spotify",
    category_slug: "subscriptions",
    slug: "spotify-premium",
    title: "اشتراك Spotify Premium",
    summary: "موسيقى بلا إعلانات وتحميل غير محدود بجودة عالية.",
    description:
      "اشتراك سبوتيفاي بريميوم على حسابك الشخصي، بدون إعلانات مع تخطي غير محدود وتحميل الأغاني للاستماع دون إنترنت.",
    price: 22,
    old_price: 35,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "تفعيل خلال 20 دقيقة",
    features: [
      "على حسابك الشخصي",
      "بدون إعلانات نهائياً",
      "تحميل غير محدود",
      "جودة صوت عالية",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 5,
  },
  {
    id: "svc-sub-youtube",
    category_slug: "subscriptions",
    slug: "youtube-premium",
    title: "اشتراك YouTube Premium",
    summary: "يوتيوب بدون إعلانات + تشغيل في الخلفية + Music.",
    description:
      "اشتراك يوتيوب بريميوم على حسابك، يشمل مشاهدة بدون إعلانات، التشغيل في الخلفية والتحميل، بالإضافة إلى YouTube Music.",
    price: 26,
    old_price: 40,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "تفعيل خلال 20 دقيقة",
    features: [
      "بدون إعلانات على كل الأجهزة",
      "تشغيل في الخلفية",
      "يشمل YouTube Music",
      "على حسابك الشخصي",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 6,
  },
  {
    id: "svc-sub-adobe",
    category_slug: "subscriptions",
    slug: "adobe-creative-cloud",
    title: "اشتراك Adobe Creative Cloud",
    summary: "فوتوشوب وإليستريتور وبريمير وكل تطبيقات أدوبي.",
    description:
      "اشتراك Adobe Creative Cloud الشامل لكل التطبيقات، مثالي للمصممين والمونتيرين، مع تفعيل على جهازك مباشرة.",
    price: 95,
    old_price: 140,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "تفعيل خلال ساعة",
    features: [
      "كل تطبيقات أدوبي",
      "تفعيل على جهازك",
      "مساحة سحابية",
      "دعم تركيب عن بُعد",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 7,
  },

  // ── بطاقات الشحن والألعاب ───────────────────────────────────────────────
  {
    id: "svc-game-pubg",
    category_slug: "gaming",
    slug: "pubg-uc",
    title: "شحن شدات ببجي UC",
    summary: "شحن مباشر بالـ ID خلال دقائق وبأرخص سعر.",
    description:
      "شحن شدات ببجي موبايل مباشرة على الـ ID الخاص بك بدون الحاجة لبيانات الدخول. كل الفئات متوفرة من 60 UC حتى 8100 UC.",
    price: 12,
    old_price: 16,
    currency: "₪",
    unit: "60 UC",
    delivery_time: "شحن خلال 5 دقائق",
    features: [
      "شحن بالـ ID فقط",
      "كل الفئات متوفرة",
      "أرخص سعر مضمون",
      "متاح 24 ساعة",
    ],
    badge: "الأكثر طلباً",
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "svc-game-freefire",
    category_slug: "gaming",
    slug: "free-fire-diamonds",
    title: "شحن جواهر فري فاير",
    summary: "جواهر فري فاير بالـ ID مع تسليم فوري.",
    description:
      "شحن جواهر فري فاير على الـ ID مباشرة، كل الفئات متوفرة مع أسعار منافسة وتسليم فوري على مدار الساعة.",
    price: 10,
    old_price: 14,
    currency: "₪",
    unit: "100 جوهرة",
    delivery_time: "شحن خلال 5 دقائق",
    features: [
      "شحن بالـ ID فقط",
      "كل الفئات متوفرة",
      "تسليم فوري",
      "متاح 24 ساعة",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 2,
  },
  {
    id: "svc-game-googleplay",
    category_slug: "gaming",
    slug: "google-play-card",
    title: "بطاقات جوجل بلاي",
    summary: "أكواد جوجل بلاي أصلية لكل المتاجر والفئات.",
    description:
      "بطاقات Google Play أصلية بفئات متعددة ومتاجر مختلفة (أمريكي، سعودي، إماراتي)، يُرسل الكود مباشرة بعد الدفع.",
    price: 40,
    old_price: null,
    currency: "₪",
    unit: "فئة 10$",
    delivery_time: "الكود خلال 10 دقائق",
    features: [
      "أكواد أصلية 100%",
      "متاجر متعددة",
      "كل الفئات متوفرة",
      "ضمان تفعيل الكود",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: "svc-game-itunes",
    category_slug: "gaming",
    slug: "itunes-card",
    title: "بطاقات آيتونز / App Store",
    summary: "بطاقات آبل أصلية لشراء التطبيقات والاشتراكات.",
    description:
      "بطاقات iTunes و App Store أصلية بكل الفئات والمتاجر، مثالية لشراء التطبيقات والألعاب والاشتراكات داخل أجهزة آبل.",
    price: 40,
    old_price: null,
    currency: "₪",
    unit: "فئة 10$",
    delivery_time: "الكود خلال 10 دقائق",
    features: [
      "بطاقات أصلية",
      "متاجر أمريكي وسعودي وإماراتي",
      "كل الفئات",
      "ضمان تفعيل",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: "svc-game-playstation",
    category_slug: "gaming",
    slug: "playstation-card",
    title: "بطاقات بلايستيشن",
    summary: "رصيد PSN واشتراكات PS Plus بكل الفئات.",
    description:
      "بطاقات شحن رصيد بلايستيشن واشتراكات PS Plus بمختلف الباقات، أكواد أصلية تُسلّم مباشرة.",
    price: 45,
    old_price: null,
    currency: "₪",
    unit: "فئة 10$",
    delivery_time: "الكود خلال 15 دقيقة",
    features: [
      "رصيد PSN واشتراكات PS Plus",
      "أكواد أصلية",
      "متاجر متعددة",
      "دعم عند التفعيل",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 5,
  },
  {
    id: "svc-game-steam",
    category_slug: "gaming",
    slug: "steam-wallet",
    title: "بطاقات ستيم Steam",
    summary: "رصيد محفظة ستيم لشراء أي لعبة على المنصة.",
    description:
      "أكواد شحن محفظة Steam بكل الفئات، تُضاف لحسابك مباشرة وتستخدمها لشراء أي لعبة أو عنصر داخل المنصة.",
    price: 42,
    old_price: null,
    currency: "₪",
    unit: "فئة 10$",
    delivery_time: "الكود خلال 15 دقيقة",
    features: [
      "أكواد أصلية",
      "كل الفئات متوفرة",
      "تُضاف للمحفظة مباشرة",
      "ضمان تفعيل",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 6,
  },
  {
    id: "svc-game-jawaker",
    category_slug: "gaming",
    slug: "jawaker-tokens",
    title: "شحن جواكر Jawaker",
    summary: "توكنز جواكر بالـ ID مع شحن فوري.",
    description:
      "شحن توكنز جواكر مباشرة على الـ ID الخاص بك، كل الفئات متوفرة بأسعار منافسة وشحن خلال دقائق.",
    price: 15,
    old_price: null,
    currency: "₪",
    unit: "فئة أساسية",
    delivery_time: "شحن خلال 10 دقائق",
    features: [
      "شحن بالـ ID",
      "كل الفئات",
      "أسعار منافسة",
      "متاح يومياً",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 7,
  },
  {
    id: "svc-game-roblox",
    category_slug: "gaming",
    slug: "roblox-robux",
    title: "شحن روبلوكس Robux",
    summary: "روبكس لحسابك في روبلوكس بشحن آمن ومباشر.",
    description:
      "شحن Robux لحساب روبلوكس الخاص بك بطريقة آمنة، مع كل الفئات المتاحة وتسليم سريع.",
    price: 20,
    old_price: null,
    currency: "₪",
    unit: "400 روبكس",
    delivery_time: "شحن خلال 30 دقيقة",
    features: [
      "شحن آمن للحساب",
      "كل الفئات",
      "أسعار تنافسية",
      "دعم فني",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 8,
  },

  // ── باقات الاتصالات ─────────────────────────────────────────────────────
  {
    id: "svc-tel-sawa-post",
    category_slug: "telecom",
    slug: "sawa-post-plus",
    title: "باقة سوا بوست بلس",
    summary: "إنترنت ومكالمات بباقة شهرية متكاملة وتفعيل فوري.",
    description:
      "باقة سوا بوست بلس الشهرية تشمل إنترنت ومكالمات ورسائل، تُفعّل مباشرة على رقمك خلال دقائق من تأكيد الطلب.",
    price: 55,
    old_price: 70,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "تفعيل خلال 10 دقائق",
    features: [
      "إنترنت ومكالمات ورسائل",
      "تفعيل مباشر على رقمك",
      "بدون عقود أو التزام",
      "تذكير قبل انتهاء الباقة",
    ],
    badge: "مميزة",
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "svc-tel-jawwal-net",
    category_slug: "telecom",
    slug: "jawwal-internet",
    title: "باقات إنترنت جوال",
    summary: "باقات نت يومية وأسبوعية وشهرية بكل الأحجام.",
    description:
      "كل باقات الإنترنت من جوال — يومية، أسبوعية وشهرية — بأحجام مختلفة تناسب استخدامك، مع تفعيل فوري.",
    price: 15,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "تفعيل خلال 10 دقائق",
    features: [
      "باقات يومية وأسبوعية وشهرية",
      "كل الأحجام متوفرة",
      "تفعيل فوري",
      "استشارة لاختيار الأنسب",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 2,
  },
  {
    id: "svc-tel-ooredoo",
    category_slug: "telecom",
    slug: "ooredoo-packages",
    title: "باقات أوريدو",
    summary: "كل باقات أوريدو للإنترنت والمكالمات بتفعيل مباشر.",
    description:
      "باقات أوريدو المتنوعة للإنترنت والمكالمات، نساعدك في اختيار الباقة الأنسب لاستخدامك ونفعّلها لك مباشرة.",
    price: 20,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "تفعيل خلال 10 دقائق",
    features: [
      "كل الباقات متوفرة",
      "تفعيل مباشر",
      "استشارة مجانية",
      "أسعار المشغّل",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: "svc-tel-topup",
    category_slug: "telecom",
    slug: "mobile-topup",
    title: "تعبئة رصيد فورية",
    summary: "تعبئة رصيد لأي شبكة بأي مبلغ خلال دقائق.",
    description:
      "تعبئة رصيد فورية لأي شبكة وبأي مبلغ تريده، أرسل الرقم والمبلغ ونحن نتكفل بالباقي.",
    price: 10,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "تعبئة خلال 5 دقائق",
    features: [
      "كل الشبكات",
      "أي مبلغ تريده",
      "تعبئة فورية",
      "متاح 24 ساعة",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: "svc-tel-esim",
    category_slug: "telecom",
    slug: "travel-esim",
    title: "شرائح eSIM للسفر",
    summary: "إنترنت أثناء السفر بدون شريحة فعلية أو تجوال باهظ.",
    description:
      "شرائح eSIM رقمية تعمل في أكثر من 100 دولة، تُفعّل بمسح كود QR وتوفر عليك رسوم التجوال المرتفعة.",
    price: 45,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "الكود خلال 30 دقيقة",
    features: [
      "أكثر من 100 دولة",
      "تفعيل بمسح QR",
      "بدون شريحة فعلية",
      "خطط بأحجام مختلفة",
    ],
    badge: "جديد",
    is_featured: false,
    is_active: true,
    sort_order: 5,
  },

  // ── الخدمات الرقمية والتصميم ────────────────────────────────────────────
  {
    id: "svc-dig-brand",
    category_slug: "digital",
    slug: "brand-identity",
    title: "تصميم هوية بصرية كاملة",
    summary: "لوقو + دليل ألوان وخطوط + تطبيقات جاهزة للطباعة والنشر.",
    description:
      "هوية بصرية متكاملة تبدأ من فهم نشاطك وجمهورك: شعار احترافي بعدة صيغ، نظام ألوان وخطوط، نمط بصري خاص، وتطبيقات جاهزة (كرت شخصي، أيقونة، أغلفة سوشيال ميديا).",
    price: 650,
    old_price: 900,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "التسليم خلال 5-7 أيام",
    features: [
      "شعار احترافي بعدة صيغ وملفات مفتوحة",
      "دليل هوية كامل (ألوان، خطوط، استخدامات)",
      "تطبيقات جاهزة للطباعة والنشر",
      "تعديلات غير محدودة حتى الرضا",
    ],
    badge: "الأكثر تميزاً",
    is_featured: true,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "svc-dig-website",
    category_slug: "digital",
    slug: "website-design",
    title: "تصميم وتطوير موقع إلكتروني",
    summary: "موقع سريع ومتجاوب يحوّل الزائر إلى عميل فعلي.",
    description:
      "موقع إلكتروني احترافي مبني بأحدث التقنيات: سريع، متجاوب مع كل الشاشات، مهيأ لمحركات البحث، ومربوط بقاعدة بيانات ولوحة تحكم تديرها بنفسك.",
    price: 1200,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "التسليم خلال 10-20 يوم",
    features: [
      "تصميم متجاوب مع كل الأجهزة",
      "تهيئة كاملة لمحركات البحث SEO",
      "لوحة تحكم لإدارة المحتوى",
      "ربط واتساب ودفع وتحليلات",
    ],
    badge: null,
    is_featured: true,
    is_active: true,
    sort_order: 2,
  },
  {
    id: "svc-dig-ads",
    category_slug: "digital",
    slug: "ads-management",
    title: "إدارة الحملات الإعلانية",
    summary: "إعلانات ممولة مدروسة تجيب نتائج حقيقية لا مجرد مشاهدات.",
    description:
      "إدارة حملاتك المموّلة على إنستقرام وفيسبوك وتيك توك: استهداف دقيق، تصاميم إعلانية جذابة، اختبار مستمر وتقارير أسبوعية توضح العائد على كل شيكل.",
    price: 450,
    old_price: null,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "انطلاق الحملة خلال 48 ساعة",
    features: [
      "استهداف دقيق حسب جمهورك",
      "تصاميم إعلانية احترافية",
      "تحسين مستمر واختبار A/B",
      "تقرير أسبوعي واضح بالنتائج",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: "svc-dig-content",
    category_slug: "digital",
    slug: "content-management",
    title: "إدارة حسابات ومحتوى",
    summary: "خطة محتوى شهرية + تصاميم + نشر + تفاعل مع الجمهور.",
    description:
      "نتولى حساباتك بالكامل: خطة محتوى شهرية مبنية على أهدافك، تصاميم ونصوص، جدولة ونشر، والرد على التعليقات والرسائل.",
    price: 550,
    old_price: 750,
    currency: "₪",
    unit: "شهرياً",
    delivery_time: "بداية العمل خلال 3 أيام",
    features: [
      "خطة محتوى شهرية مكتوبة",
      "16 تصميم + نصوص شهرياً",
      "جدولة ونشر منتظم",
      "إدارة التعليقات والرسائل",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: "svc-dig-logo",
    category_slug: "digital",
    slug: "logo-design",
    title: "تصميم شعار احترافي",
    summary: "شعار مميز بعدة مقترحات وملفات مفتوحة بجودة لا نهائية.",
    description:
      "تصميم شعار احترافي يبدأ بثلاثة مقترحات مختلفة، تختار منها ونطوّره حتى الشكل النهائي، مع تسليم كل الصيغ والملفات المفتوحة.",
    price: 250,
    old_price: 350,
    currency: "₪",
    unit: null,
    delivery_time: "التسليم خلال 3-5 أيام",
    features: [
      "3 مقترحات مختلفة",
      "تعديلات حتى الرضا التام",
      "كل الصيغ (PNG, SVG, PDF, AI)",
      "نسخ ملونة وأحادية اللون",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 5,
  },
  {
    id: "svc-dig-video",
    category_slug: "digital",
    slug: "video-editing",
    title: "مونتاج فيديو وريلز",
    summary: "ريلز وإعلانات بمونتاج سريع الإيقاع يوقف السكرول.",
    description:
      "مونتاج احترافي للريلز والإعلانات القصيرة: قص سريع الإيقاع، مؤثرات، موسيقى، ترجمة وحركة نصوص تجذب الانتباه في أول ثانيتين.",
    price: 120,
    old_price: null,
    currency: "₪",
    unit: "للفيديو",
    delivery_time: "التسليم خلال 48 ساعة",
    features: [
      "مونتاج سريع الإيقاع",
      "ترجمة وحركة نصوص",
      "موسيقى ومؤثرات",
      "جولتا تعديل مجانيتان",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 6,
  },
  {
    id: "svc-dig-store",
    category_slug: "digital",
    slug: "online-store",
    title: "إنشاء متجر إلكتروني",
    summary: "متجر متكامل بسلة ودفع ولوحة تحكم وربط واتساب.",
    description:
      "متجر إلكتروني جاهز للبيع من اليوم الأول: عرض منتجات، سلة شراء، طرق دفع، إدارة طلبات، وربط مباشر بالواتساب لتحويل الزوار إلى طلبات.",
    price: 1800,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "التسليم خلال 14-21 يوم",
    features: [
      "سلة شراء وإدارة طلبات",
      "ربط واتساب وطرق الدفع",
      "لوحة تحكم كاملة",
      "تدريب على الاستخدام",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 7,
  },

  // ── خدمات أخرى ──────────────────────────────────────────────────────────
  {
    id: "svc-oth-verify",
    category_slug: "other",
    slug: "account-verification",
    title: "توثيق الحسابات",
    summary: "العلامة الزرقاء لحسابك على إنستقرام أو تيك توك أو فيسبوك.",
    description:
      "خدمة توثيق الحسابات بالعلامة الزرقاء عبر تجهيز ملف الحساب والمستندات وتقديم الطلب بالطريقة الصحيحة لرفع فرص القبول.",
    price: 900,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "المدة 7-21 يوم",
    features: [
      "تجهيز كامل لملف الحساب",
      "مراجعة المستندات قبل التقديم",
      "متابعة الطلب حتى النتيجة",
      "استشارة مجانية قبل البدء",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 1,
  },
  {
    id: "svc-oth-recovery",
    category_slug: "other",
    slug: "account-recovery",
    title: "استرجاع الحسابات",
    summary: "استرجاع الحسابات المسروقة أو المغلقة أو المنسية.",
    description:
      "خدمة استرجاع الحسابات المخترقة أو المغلقة أو التي فقدت الوصول إليها، بطرق رسمية مع متابعة الطلب حتى استعادة الحساب.",
    price: 150,
    old_price: null,
    currency: "₪",
    unit: "تبدأ من",
    delivery_time: "المدة 1-7 أيام",
    features: [
      "طرق رسمية وآمنة",
      "يشمل الحسابات المخترقة والمغلقة",
      "متابعة حتى النتيجة",
      "لا تدفع إلا عند النجاح",
    ],
    badge: "مضمون",
    is_featured: true,
    is_active: true,
    sort_order: 2,
  },
  {
    id: "svc-oth-security",
    category_slug: "other",
    slug: "account-security",
    title: "حماية وتأمين الحسابات",
    summary: "إقفال حسابك أمام محاولات الاختراق قبل ما تصير المشكلة.",
    description:
      "مراجعة أمنية شاملة لحساباتك: تفعيل التحقق بخطوتين، مراجعة الجلسات والتطبيقات المرتبطة، تقوية كلمات المرور وإعداد خطة استرجاع.",
    price: 80,
    old_price: null,
    currency: "₪",
    unit: "للحساب",
    delivery_time: "التنفيذ خلال ساعتين",
    features: [
      "تفعيل التحقق بخطوتين",
      "مراجعة الجلسات والتطبيقات",
      "خطة استرجاع جاهزة",
      "تقرير أمني مبسّط",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 3,
  },
  {
    id: "svc-oth-domain",
    category_slug: "other",
    slug: "domain-hosting",
    title: "دومين واستضافة",
    summary: "حجز اسم النطاق واستضافة سريعة مع إعداد كامل.",
    description:
      "حجز اسم النطاق المناسب لنشاطك مع استضافة سريعة وشهادة SSL وإيميلات باسم موقعك، وإعداد كامل جاهز للانطلاق.",
    price: 180,
    old_price: null,
    currency: "₪",
    unit: "سنوياً",
    delivery_time: "الإعداد خلال 24 ساعة",
    features: [
      "دومين + استضافة + SSL",
      "إيميلات باسم موقعك",
      "إعداد كامل جاهز",
      "دعم التجديد السنوي",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 4,
  },
  {
    id: "svc-oth-vpn",
    category_slug: "other",
    slug: "vpn-subscription",
    title: "اشتراك VPN",
    summary: "تصفح آمن وسريع مع سيرفرات في كل دول العالم.",
    description:
      "اشتراك VPN موثوق بسرعات عالية وسيرفرات في عشرات الدول، يعمل على كل الأجهزة مع حماية كاملة للخصوصية.",
    price: 35,
    old_price: 50,
    currency: "₪",
    unit: "سنوياً",
    delivery_time: "تفعيل خلال 15 دقيقة",
    features: [
      "سيرفرات في عشرات الدول",
      "يعمل على كل الأجهزة",
      "سرعات عالية",
      "بدون تسجيل نشاط",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 5,
  },
  {
    id: "svc-oth-consult",
    category_slug: "other",
    slug: "digital-consultation",
    title: "استشارة رقمية",
    summary: "جلسة مباشرة نضع فيها خطة واضحة لحضورك الرقمي.",
    description:
      "جلسة استشارية مباشرة نراجع فيها وضعك الحالي ونضع خطة عملية واضحة: من أين تبدأ، على أي منصة تركز، وما الميزانية المطلوبة.",
    price: 100,
    old_price: null,
    currency: "₪",
    unit: "للجلسة",
    delivery_time: "حجز خلال 24 ساعة",
    features: [
      "جلسة 60 دقيقة مباشرة",
      "تحليل وضعك الحالي",
      "خطة عملية مكتوبة",
      "قيمة الجلسة تُخصم عند التعاقد",
    ],
    badge: null,
    is_featured: false,
    is_active: true,
    sort_order: 6,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "محمود أبو ندى",
    handle: "صاحب متجر ملابس",
    rating: 5,
    body: "طلبت متابعين وباقة إدارة محتوى، خلال شهر صار عندي طلبات يومية من الإنستقرام. التعامل محترم والتسليم بوقته بالضبط.",
  },
  {
    id: "t2",
    name: "سُلاف حرب",
    handle: "مصممة أزياء",
    rating: 5,
    body: "الهوية البصرية اللي عملولي غيّرت شكل مشروعي تماماً. حسّيت إنهم فهموا الفكرة أكثر مني.",
  },
  {
    id: "t3",
    name: "أحمد ياسين",
    handle: "لاعب ومنشئ محتوى",
    rating: 5,
    body: "أشحن شدات من عندهم من سنة تقريباً. أرخص سعر لقيته والشحن ما تأخر ولا مرة وحدة.",
  },
  {
    id: "t4",
    name: "رنا الأغا",
    handle: "صاحبة مشروع حلويات",
    rating: 5,
    body: "أخذت يوزر رباعي للحساب وكانت العملية مرتبة وواضحة من أولها لآخرها. ثقة من أول تعامل.",
  },
  {
    id: "t5",
    name: "كريم دولة",
    handle: "مدير تسويق",
    rating: 5,
    body: "أفضل شي فيهم إنهم بيردوا بسرعة على الواتساب. سألت عشرين سؤال قبل ما أطلب وما زهقوا.",
  },
  {
    id: "t6",
    name: "ليان مقداد",
    handle: "طالبة جامعية",
    rating: 5,
    body: "اشتركت كانفا برو وشات جي بي تي منهم، اشتغلوا من أول دقيقة وبنص السعر اللي كنت رح أدفعه.",
  },
];

// ── helpers ────────────────────────────────────────────────────────────────

export function getCategory(slug: string) {
  return categories.find((c) => c.slug === slug) ?? null;
}

export function getService(slug: string) {
  return services.find((s) => s.slug === slug) ?? null;
}

export function servicesByCategory(slug: string) {
  return services
    .filter((s) => s.category_slug === slug && s.is_active)
    .sort((a, b) => a.sort_order - b.sort_order);
}

export function countByCategory(slug: string) {
  return services.filter((s) => s.category_slug === slug && s.is_active).length;
}
